apiVersion: v1
kind: Service
metadata:
  name: phpapp
  namespace: webapp-namespace
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:us-east-2:XXXXXXXX:certificate/c92f5902-f6a7-439d-82d1-4de032b61fad
    # Only run SSL on the port named "https" below.
  labels:
    app: phpapp
    environment: test
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
  selector:
      app: phpapp
      environment: test
